### PR TITLE
Fix JSON syntax highlighting. Support for up to 30 levels deep.

### PR DESCRIPTION
**Pull request by jonsuh**
Noticed that based on the data, JSON syntax highlighting was inconsistent. Here’s a proposed fix that supports consistent syntax highlighting and for up to 30 levels deep.

image

## The fix

Here’s a look at the fix:

```
      <key>name</key>
      <string>JSON: Value</string>
      <key>scope</key>
      <string>source.json meta.structure.dictionary.json meta.structure.dictionary.value.json string.quoted.double.json</string>
...
      <key>name</key>
      <string>JSON: Key</string>
      <key>scope</key>
      <string>source.json meta.structure.dictionary.json string.quoted.double.json</string>
```

However, this only supports JSON that goes one level deep. To support multiple levels, we add `meta` after `source.json` in `<string>` for every level deep, separating each level with a comma, and going backwards (deepest to shallowest):

Here’s `JSON: Value` for example (For readability, I added line breaks)

```
<string>
source.json meta meta meta meta.structure.dictionary.json meta.structure.dictionary.value.json string.quoted.double.json,
source.json meta meta meta.structure.dictionary.json meta.structure.dictionary.value.json string.quoted.double.json,
source.json meta meta.structure.dictionary.json meta.structure.dictionary.value.json string.quoted.double.json,
source.json meta.structure.dictionary.json meta.structure.dictionary.value.json string.quoted.double.json
</string>
```

### CODE REVIEW

**Comment by Revod** [comment]
wow, love it

**Comment by ZakariaRidouh** [comment]
Great job!

**Comment by equinusocio** [comment]
... i like your support but you don't think that `key: "string value"` should have a different color from `key: false`?

**Comment by jonsuh** [comment]
@equinusocio Ahaha, oh my—maybe I was hungry and thinking about “double meat...” `meat` changed to `meta`.

Not a bad idea about differentiating `true/false`. How about this change? We’ll do JSON true/false as the same color as Booleans foreground and double-quoted string values as Variable foreground.

image

**Comment by equinusocio** [comment]
@jonsuh Better!

**Comment by jonsuh** [comment]
@equinusocio There *might* be another solution, but I’m not sure—I’m no expert and this was the only thing I was able to get to work.

**Pull request merged**
