### PR TITLE
Ligter line number font for better visibility

### PR DESCRIPTION
**Pull request by hanxue**
See #139
Change line number to lighter color for better contrast

### CODE REVIEW

**Comment by hanxue** [comment]
Before

screen shot 2015-06-17 at 11 23 34 am

After

screen shot 2015-06-17 at 12 06 20 pm

**Comment by equinusocio** [comment]
In the last relese the linehighlight was fixed.

screen shot 2015-06-17 at 09 04 49

**Comment by hanxue** [comment]
@equinusocio Thanks of the quick reply. In your screenshot, I can barely see the line number. Line highlighting was working, but the contrast between line number and gutter background is still too low.

**Comment by equinusocio** [comment]
You can fork this theme and made your own version ;) i can't think to fix every "personal fancy". Sorry.

**Pull request closed without merging**
