### PR TITLE
temporary fix #1128

### LINKED ISSUE #1128: High CPU usage when using 3131
### Summary

Since updating to 3131, the energy impact / cpu used by Sublime has been constantly very high. Reverting to a freshly installed state helped. Once I reinstalled Material Theme, the CPU troubles began again. Once I reset the theme to be default, the CPU troubles went away.

### Expected behavior

Using Material theme shouldn't be taxing on the CPU.

### Actual behavior

Using Material theme is taxing on the CPU.

### Steps to reproduce

1. Have a freshly installed copy of Sublime text 3131
2. Install and activate Material theme
3. Observe the high CPU load.

### Environment

* Operating system and version:
  * [x] Mac OS 10.12.4
* Sublime Text:
  * Build 3131
* Material Theme release:
  * 4.0.6

Info copied from Material Theme: Info

* Sublime Text:   3131
* Platform:   osx
* Arch:   x64
* Theme:   4.0.6
* Install via PC:   True
* Dependencies:
    * mdpopups:   1.13.1
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

### PR DESCRIPTION
**Pull request by kawasako**
Disable styles of title_bar

#### Description
I have found the cause of this problem.
Deleting "title_bar" class solved the problem.
In my opinion this is a problem of ST3 or OSX.

I temporarily stopped functioning until this problem is resolved.

#### Motivation and Context

#1128

#### How Has This Been Tested?

Use OSX Activity Monitor.

The styles will no longer apply to titlebar.

#### Screenshots (if appropriate):
sublime

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wbond** [comment]
Does this fix still work if all you comment out is the title bar rule that is triggered by a setting?

**Comment by equinusocio** [comment]
@kawasako Thank you for you help. @wbond what is the setting to switch native title bar? i can't find it on 3143

**Comment by wbond** [comment]
In `sources/themes/commons/accent.json` there is a `title_bar` rule that has `settings`. That means the rule will only be applied when a setting is true. I was just curious if the performance issue was somehow related to the rule being filtered by a setting.

**Comment by equinusocio** [comment]
Oh ok. I think it is not related because i added that setting just 20 days ago. This issue https://github.com/equinusocio/material-theme/commit/2b57e5f47badd5a8cea7ac9c78b70ded99f3987a was opened 6 months ago after build 3131

**Pull request merged**
