### PR TITLE
Update dependencies and fix bump tasks issue

### PR DESCRIPTION
**Pull request by zpreston123**
#### Description

- Updated Node dependencies to their latest version.
- Fixed Gulp bump tasks not updating the version number in package.json or info.py, depending on the task being run.  This includes passing a custom version key to bump() in the "bump-env-version" task and removing the "--patch" flag, since the default type is patch when a task is run without the "--major" or "--minor" flag.  Also, the default argument length for the tasks is four instead of two.
- Added NPM bump script to package.json for convenience.

#### Motivation and Context

This ensures the Node dependencies are up-to-date.  Also resolves an issue with Gulp displaying an error or not updating the version number in package.json or info.py;  it was caused by the regular expression defined in bump.js, which closely matched the regular expression defined in the bump-regex module.

#### How Has This Been Tested?

This was tested using PackageDev, NPM, and Gulp.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by zpreston123** [comment]
@equinusocio Do I need to push the release to develop and merge it into master or just push it to master?

**Comment by equinusocio** [comment]
Build develop and the merge with master. Then male the release from master. Don’t forget the bump and the changelog

**Comment by zpreston123** [comment]
OK, does that mean I need to make another Pull Request before merging develop into master?

**Comment by equinusocio** [comment]
Yes :)

**Comment by zpreston123** [comment]
Cool thanks!  I pushed some changes, including the bump and changelog directly to develop, and submitted a Pull Request.

**Pull request merged**
