### PR TITLE
Fix disabled folder animations for all themes

### LINKED ISSUE #943: New color accents issues on open folder hover and tooltips
### Summary

If you select one of the new accent color added (sky, bright-teal, acid-lime, brba, tomato) the hover color keeps to stay teal (see screenshot), also the tooltip font color stays white and gives legibility issues

schermata 2016-08-08 alle 15 57 52
schermata 2016-08-08 alle 15 55 55
schermata 2016-08-08 alle 15 55 34

### Expected behavior

The folder color is expected to be the same as the accent color (as all others folders and old color accents do)

### Actual behavior

the hover on the open folder keeps being teal

### Steps to reproduce

1. Change accent color
2. hover on an open folder

### Environment

* Operating system and version:

  * Mac OS El Capitan 10.11.5

* Sublime Text:
  * Build 3114
* Material Theme release:
  * v3.1.6

### PR DESCRIPTION
**Pull request by anhuynh**
#### Description

Fixes disabled folder animations for all themes. Disabled folder animation code for all accent colours were added back that was deleted in b7446c299a4b0700d56be791eb3efabd9b8bd674. Also adds missing disabled folder animation code for the newer accent colours. Little bit of spelling also fixed in the README.

#### Motivation and Context

b7446c299a4b0700d56be791eb3efabd9b8bd674 did not actually fix #943 properly. I noticed that even when I had folder animations disabled and using the dark or light theme, the animations were still there. Additionally, on the default theme, all accents would have the default teal coloured folder when hovering over with folder animations disabled (see screenshot).

#### How Has This Been Tested?

I installed the changed theme over the old themes and then checked most of the accents on each of the themes to ensure that the folder animation worked.

#### Screenshots (if appropriate):
Using Default theme with red accent:

diff

I don't have a gif of the disabled folder animation issue on the Darker and Lighter themes.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by diego1araujo** [comment]
I've tested all accent colors in the current version named v3.1.8 on ST3 3114/Windows 10 and it looks like is everything ok.

Can you say which version of MT, ST and OS you are running?

**Comment by anhuynh** [comment]
@diego1araujo That's weird. I first noticed the issue on v3.1.7 on OSX 10.11.6/ST3 3114. I can also see the behaviour on my Windows 10/ST3 3114 too. Did you disable folder animations? Cause that's where the issue happens.

**Comment by diego1araujo** [comment]
Ohh, now I see. You wrote "Default theme" but picture example seems like Darker theme. That confused me hard.

Yes, on default it happens. This might be merged soon. :+1:

**Comment by anhuynh** [comment]
Yeah, there's also an issue with the Darker and Lighter themes too. Disabling folder animations on those themes don't do anything. This fixes that as well as the screenshotted issue on the Default theme.

**Comment by equinusocio** [comment]
Thanks! :)

**Pull request merged**
