### PR TITLE
Fix build tasks and color scheme files

### PR DESCRIPTION
**Pull request by zpreston123**
#### Description

This is just a small patch:

- Fixed some tasks in the theme builder to convert the scheme files to .yml files, since it affected some of them in the previous changes.
- Removed .yml files in the schemes folder, since they are used for development.
- Fixed a minor scope typo and included the latest changes in the scheme.yml file.
- Changed the PlainTasks scheme .YAML-tmTheme extension to .yml. 
- Updated .gitignore file, which includes ignoring .yml files in the schemes folder.

#### Motivation and Context

This ensures the scheme files are compiled to .yml instead of the original .YAML-tmTheme extension.  This also fixes a typo in the scheme file, so it doesn't produce unexpected results.  The .gitignore file was updated to remove the old build folder and images.cache file (.cache files are ignored via *.cache);  also ignores the .yml files in the schemes folder, so they don't get pushed with the converted files.

**Note**:  Not sure which extension you prefer to keep?  I can revert to .YAML-tmTheme if you want.

#### How Has This Been Tested?

These changes were tested using PackageDev, NPM, and Gulp.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by zpreston123** [comment]
@equinusocio When you get a chance, let me know what you think.

**Comment by equinusocio** [comment]
@zpreston123 Thanks for the ping. I totally missed this PR. Nice work.

**Comment by zpreston123** [comment]
@equinusocio No problem, thank you.  I will push the bump, changelog, and messages in a separate PR for the next release.

**Comment by zpreston123** [comment]
@equinusocio I tried generating the changelog, but it overwrote the previous tag with the new one, and merged the previous "Bug Fixes" with the latest ones.  Also removed the "Breaking Changes" section relative to the previous tag.  Have you faced a similar issue?

screen shot 2018-02-11 at 11 51 25 am

**Comment by zpreston123** [comment]
@equinusocio I tried generating the changelog, but I got this output as a result:
screen shot 2018-02-11 at 8 04 48 pm

Did you encounter a similar issue when running the changelog command?

**Comment by equinusocio** [comment]
Yes sometime this occurs and i don't know why. Just let it as is, don't worry. Just write the update message with the relative updates.

**Comment by zpreston123** [comment]
@equinusocio OK all set.

**Pull request merged**
