### PR TITLE
Add new port for Atom

### PR DESCRIPTION
**Pull request by leo**
I've created [another version][1] of your theme for GitHub's Atom editor. Therefore I thought it might be a great idea to link it here, too (along with the existing one).

[1]: https://atom.io/themes/material-ui

### CODE REVIEW

**Comment by equinusocio** [comment]
Hi @leo please add your porting under the @silvestreh one. :+1:

**Comment by leo** [comment]
@equinusocio Look closer, they're both still there :blush:

**Comment by equinusocio** [comment]
You're right. Sorry. :+1:  Thanks for your work :)

**Comment by leo** [comment]
@equinusocio No problem! Thank you too for merging it! :smile_cat:

**Pull request merged**
