### PR TITLE
Comment Coloring

### PR DESCRIPTION
**Pull request by rouzbeh84**
#### Description

This PR gives the comments a sightly darker background from the Material Darker theme an a bright green color to make comments much clearer to readers.

#### Motivation and Context

I feel that comments shouldn't be faded out but rather standout so while reasoning about the code you can easily spot them and understand what's going on

#### How Has This Been Tested?

I added it locally and haven't seen any issues whatsoever across various file types

#### Screenshots (if appropriate):

screenshot of comments

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by rouzbeh84** [comment]
Would like to eventually make the text color an option of the advanced configuration if this is something you'd be interested in.

**Comment by equinusocio** [comment]
Hi @rouzbeh84, they are allowed bugfixing PR, not personal customization. You can do this customization in your local installation. Sorry for that.

**Comment by rouzbeh84** [comment]
No problem! I didn't know the guidelines but thought it was a useful addition. If I wanted to make that an option in the config where would I begin to look if you don't mid me asking?

**Comment by equinusocio** [comment]
You can't make an option to handle scheme colors. You can only set the default comments color for each theme:
https://github.com/equinusocio/material-theme/tree/develop/sources/settings/specific

**Pull request closed without merging**
