### PR TITLE
fix: jade icon

### PR DESCRIPTION
**Pull request by vikjam**
Jade files were showing up with a text icon instead of Jade icon.

Before:
screen-before

After:
screen-after

### CODE REVIEW

**Comment by equinusocio** [comment]
Can you use the [official logo](http://jade-lang.com/style/jade-logo-header.svg)? You can try with the rabbit only or the Jade word. 
 
Are you use Sketch on OS X?

**Comment by vikjam** [comment]
I could give it a shot! The icon in the screenshot above is the one that already exists in your [theme](https://github.com/equinusocio/material-theme/blob/develop/icons/file_type_jade%402x.png).

I usually use Illustrator, but I've played around with Sketch.

**Comment by equinusocio** [comment]
With Sketch, please use this source file to make the new icon. Create or duplicate a new artboard with a correct name and use one of the common color style provided with the file (Red, blue, yellow and others..). Then export the icon `@1x.png` and `@2x.png`.

[MaterialTheme-File-Icons.zip](https://github.com/equinusocio/material-theme/files/230470/MaterialTheme-File-Icons.zip)

**Comment by vikjam** [comment]
I had a go at the rabbit using the color scheme in the Sketch file. I replaced the existing Jade logo in the Sketch file with the rabbit. Should I sent you the updated Sketch file?

jade-darker
jade-default
jade-lighter

**Comment by equinusocio** [comment]
You can move the rabbit logo of 1 or 2 pixel up? Then just export the icons using Sketch export functionality and update the PR :)

**Comment by vikjam** [comment]
How about this?

screen shot 2016-04-22 at 1 29 16 pm

**Comment by vikjam** [comment]
I updated the pull request and I'm including the updated Sketch file.

[MaterialTheme-File-Icons.zip](https://github.com/equinusocio/material-theme/files/234795/MaterialTheme-File-Icons.zip)

**Comment by equinusocio** [comment]
👍 Thanks

**Comment by psullivan6** [comment]
Since this was a recent update, I wanted to make sure you all were aware that Jade recently changed to Pug as per some legal issues. [Read about it here](https://github.com/pugjs/pug/issues/2184).

Also, for this particular GitHub Issue, the new logo can be found via [this Issue thread](https://github.com/pugjs/pug/issues/2189#issuecomment-205863725) with the [new icon repo here](https://github.com/pugjs/pug-logo).

Hopefully this helps and doesn't create too much additional work.

**Comment by equinusocio** [comment]
@psullivan6 thanks so much. I will add the pug icon and the `.pug` (i think?) icon association.

I opened a new issue here. 
https://github.com/equinusocio/material-theme/issues/773

**Comment by vikjam** [comment]
Eek--I had no idea about their rebranding. Sorry for not knowing about that! If you want, I could put together the pull request for #773.

**Comment by equinusocio** [comment]
@vikjam make sure that the new file extension is `.pug`, update the icons and the relative file
https://github.com/equinusocio/material-theme/blob/develop/prefs/icon_jade.tmPreferences

The icon must be monochromatic, i suggest you the pale yellow color.

**Pull request merged**
