### PR TITLE
Fix BracketHighlighter styles and color schemes; enable accent_titlebar option

### PR DESCRIPTION
**Pull request by zpreston123**
#### Description

- Fixed BracketHighlighter default style; added styles for other regions (i.e. curly, square, etc.).
- Enabled accent_titlebar option; white text on mild bg colors and black text on bright bg colors.
- Converted lowercase scheme hex values to uppercase for consistent format.
- Restored missing PlainTasks scheme files.
- Minor README updates.

#### Motivation and Context

This overrides all the BracketHighlighter styles based on the chosen color scheme; must be enabled in BH user settings via “user_bracket_styles” option.  This also activates the accent_titlebar option, since it was commented previously.  Some of the scheme hex values were lowercase and got converted to uppercase for consistent format.  Finally, this restores the PlainTasks scheme files missing in the “extras/PlainTasks” location.

#### How Has This Been Tested?

These changes were tested using PackageDev, NPM, Gulp, BracketHighlighter, PlainTasks, and dillinger.io.

#### Screenshots (if appropriate):
Default
screen shot 2017-11-27 at 6 04 44 pm

Darker
screen shot 2017-11-27 at 6 05 07 pm

Lighter
screen shot 2017-11-27 at 6 05 30 pm

Palenight
screen shot 2017-11-27 at 6 05 35 pm

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by equinusocio** [comment]
Thank you @zpreston123

**Comment by zpreston123** [comment]
@equinusocio OK sure.  I changed the blue indicators to pale blue, the red indicators pink, and the purple indicators violet.  Let me know what you think.

Default
screen shot 2017-12-11 at 10 37 52 am

Darker
screen shot 2017-12-11 at 10 37 42 am

Lighter
screen shot 2017-12-11 at 10 37 56 am

Palenight
screen shot 2017-12-11 at 10 38 04 am

**Comment by equinusocio** [comment]
@zpreston123 Wait wait, don't change the colors, just set the rgba opacity :)

**Comment by zpreston123** [comment]
@equinusocio OK no problem.  Thanks for clarifying.

**Comment by equinusocio** [comment]
Can you try with 30% and 50%? Just for a comparison

**Comment by zpreston123** [comment]
@equinusocio Here you go:

Default - 30% opacity
default-30
Default - 50% opacity
default-50

Darker - 30% opacity
darker-30
Darker - 50% opacity
darker-50

Lighter - 30% opacity
lighter-30
Lighter - 50% opacity
lighter-50

Palenight - 30% opacity
palenight-30
Palenight - 50% opacity
palenight-50

**Comment by equinusocio** [comment]
@zpreston123 I think the 30% is less distracting. What do you think?

**Comment by zpreston123** [comment]
@equinusocio I think 30% is a bit too dim and isn't as clear as the 50%.

**Comment by equinusocio** [comment]
Do you think that these icons should be so much visible and so much distracting? I think they add a lot of noise..

**Comment by zpreston123** [comment]
I just think they'd be a bit easier to see when viewing them that way.  However, I'm totally fine with whatever one you think would work best for the users.

**Comment by equinusocio** [comment]
We can start with 30% and waiting for issues. Issues are disabled on this repo, if you want to keep support and release fixes on this theme you can reopen them, but i don't have time to support you in complex tasks.

**Comment by zpreston123** [comment]
@equinusocio OK sounds good.  Will make that change and push it today.

**Comment by zpreston123** [comment]
@equinusocio OK all set.

**Comment by equinusocio** [comment]
@zpreston123 build the theme before merge :)

**Comment by zpreston123** [comment]
@equinusocio I ran the build command and everything looked the same, even after converting the scheme files.  If you check out the previous commits, they include the generated scheme and theme files.  Not sure if I'm missing anything.

**Comment by equinusocio** [comment]
@zpreston123 Yes sorry.

**Comment by equinusocio** [comment]
Do you want to make the release?

**Comment by zpreston123** [comment]
Sure!  I tried running "gulp bump --patch", but got this error:
```
events.js:161
      throw er; // Unhandled 'error' event
      ^
Error: Invalid semver
```
Has this happened to you before?

**Comment by equinusocio** [comment]
Make sure these two files have the same version and try just `gulp bump`
- package.json
- utils/info.py

**Comment by zpreston123** [comment]
I checked both files and they have version 4.1.2.  Same error occurred when I ran the bump command.  Think the Node dependencies are out of date.

**Comment by equinusocio** [comment]
You can try to update them. :) :P

**Comment by zpreston123** [comment]
I updated the dependencies to their latest version and ran the patch command, but same error occurred.  Think there is a bug in the bump.js file.  It updates the version in package.json, but not in utils.py.  Also, when you run "gulp bump", "gulp bump-pkg-version", or "gulp bump-env-version", the version doesn't change either.

**Pull request merged**
