### PR TITLE
More visible line numbers

### PR DESCRIPTION
**Pull request by Lykegenes**
Hi!

The line number color was very hard to see using the regular theme, so I changed it to be the same color as the files in the sidebar (without hover/selection).

I hope you like it!

Thanks,

### CODE REVIEW

**Comment by msrafi** [comment]
+1

**Comment by equinusocio** [comment]
You have to see the line number only when you need it. There is no reason to make it always visible and distracting. I can change this for a personal preference. Nothing personal.

You can make this change on your local copy, by overwriting the theme folder.

**Comment by Lykegenes** [comment]
I understand. It was just a suggestion since the darker version has more contrast when it comes to line numbers, but i prefer the blueish background color of the default one. Thanks for the great theme!

**Comment by equinusocio** [comment]
thanks man. I'm sorry

**Pull request closed without merging**
