### PR TITLE
Merge develop

### PR DESCRIPTION
**Pull request by equinusocio**
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by zpreston123** [comment]
@equinusocio OK all set.

**Comment by equinusocio** [comment]
@zpreston123 Ok You can now draft the github release :)

**Comment by zpreston123** [comment]
@equinusocio You're welcome!  Just created the release with the recent changelog messages.  A new theme for Sublime sounds great!

**Comment by equinusocio** [comment]
@zpreston123 You know python? I think that if we want to keep Material Theme a live project, we need to completely rewrite it, but we need a python developer as active contributor.

**Comment by zpreston123** [comment]
@equinusocio I only know Python at a very basic level.

**Pull request merged**
