### PR TITLE
stackGuide tag fix

### PR DESCRIPTION
**Pull request by fcaldera**
Stack guides are not working properly. The issue is the setting name used: should be `stackGuide` not `stackGuides` 

#### Description
Tab name were changed in both regular and YAML schemes templates.

#### Motivation and Context
It makes the active guide relevant. Currently there is no difference between the stack guides and the active guide 

#### How Has This Been Tested?
I couldn't. For some reason the *.tmTheme were deleted and weren't not generated again. However the YAML file were build successfully. Sorry for that!

However I changed the original build on the installed package and I notice it worked.

#### Before
image

#### After
image

#### Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by anhuynh** [comment]
I believe that you need to have PackageDev installed in your Sublime in order to generate the .tmTheme files. You should re-build and commit those back into your pr.

**Comment by fcaldera** [comment]
Thanks @anhuynh. It did work. I've added the missing .thTheme files.

**Comment by equinusocio** [comment]
To collaborate you have to edit only the files inside the `./src` folder, then run `gulp build`. I will fix this by myself, thanks!

**Comment by fcaldera** [comment]
Sure @equinusocio, that's what I did. Other files were changed by the build process.

**Comment by equinusocio** [comment]
Yes, but `schemes/Material-Theme-*.tmTheme` was removed

**Pull request closed without merging**
